### ISSUE TITLE
test failed on ramda project with mocha

### ISSUE THREAD

**Issue by guysaar223** [teambit/bit-envs#40]
`$ bit test`
````
error: bit failed to test index@0.25.0 with the following exception:
Unexpected token export
/Users/guysaar/Documents/PROJECT-RESOLVE-MODULES/50projects/ramda/dist/source/index.js:1
(function (exports, require, module, __filename, __dirname) { export { default as F } from './F';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
[ramda_bitjson_bitmap.tar.gz](https://github.com/teambit/bit-envs/files/2460115/ramda_bitjson_bitmap.tar.gz)

**Comment by GiladShoham** [comment]
That's really weird.. how does the dist files have an export from? maybe the compiler configuration was wrong?
