### ISSUE TITLE
error on 'bit test' mocha on material-ui

### ISSUE THREAD

**Issue by guysaar223** [teambit/bit-envs#48]
```
bit test
⡀⠀ loading components(node:39258) UnhandledPromiseRejectionWarning: bit.test-envs/testers/mocha@0.0.26
    at ExtensionGetDynamicConfigError.ExtendableBuiltin (/usr/local/lib/node_modules/bit-bin/dist/error/abstract-error.js:49:28)
    at ExtensionGetDynamicConfigError.AbstractError (/usr/local/lib/node_modules/bit-bin/dist/error/abstract-error.js:80:116)
    at ExtensionGetDynamicConfigError.ExternalError (/usr/local/lib/node_modules/bit-bin/dist/error/external-error.js:27:116)
    at new ExtensionGetDynamicConfigError (/usr/local/lib/node_modules/bit-bin/dist/extensions/exceptions/extension-get-dynamic-config-error.js:27:150)
    at Function._callee7$ (/usr/local/lib/node_modules/bit-bin/dist/extensions/env-extension.js:630:23)
    at tryCatch (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/bit-bin/dist/extensions/env-extension.js:167:191)
    at /usr/local/lib/node_modules/bit-bin/dist/extensions/env-extension.js:167:437
(node:39258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:39258) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
bit.test-envs/testers/mocha@0.0.26




```

project:
https://github.com/mui-org/material-ui

commit hash:
253ee269187cb93f96ac0ff4cb76ab871f35591f

bit json and bitmap:
[material-ui-json.tar.gz](https://github.com/teambit/bit-envs/files/2464543/material-ui-json.tar.gz)

**Comment by GiladShoham** [comment]
Few updates - 
1. The raw config are currently something like:
```js
{
            "bit.test-envs/testers/mocha@0.0.26": {
                "rawConfig": {
                    "require": ["@babel/register"],
                    "require": ["test/utils/setup.js"]
                }
            }
        }
```
The setup file should be under filesRequire config (or something like this) 
2. Since we need the file to exists also on consumer / imported environment we should make sure the user added it to the file in the config - we should show an error tell the user to add it if it's not there as well.
