### ISSUE TITLE
error on bulid react bootstrap

### ISSUE THREAD

**Issue by guysaar223** [teambit/bit-envs#58]
after run 
`bit build
`
```
error: bit failed to load bit.test-envs/compilers/webpack@0.0.28 with the following exception:
Cannot find module 'webpack-node-externals'.
Error: Cannot find module 'webpack-node-externals'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/guysaar/Documents/PROJECT-RESOLVE-MODULES/50projects/react-bootstrap/.git/bit/components/compilers/webpack/bit.test-envs/0.0.28/dist/src/webpack/default-config.js:15:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)


```

bit json and bitmap:
[react-bootstrap.tar.gz](https://github.com/teambit/bit-envs/files/2478310/react-bootstrap.tar.gz)

**Comment by imsnif** [comment]
Hi @guysaar223 - looks to me like the attached `.bitmap` file is empty. For that reason I am not able to build this commit hash. Getting "nothing to build" when entering "bit build". Did I misunderstand you?

**Comment by cbvictorio** [comment]
Have you tried importing a compiler for your components? I was having kind of similar issues as you, and importing a new compiler solved my issues. You can check it out on the next link:

https://docs.bitsrc.io/docs/building-components.html
