### ISSUE TITLE
jest (0.0.41) not working with setupfile - reactstrap 

### ISSUE THREAD

**Issue by guysaar223** [teambit/bit-envs#71]
project: [https://github.com/reactstrap/reactstrap](url)
commit hash: 2caaaa502eaac20b1a8843ce0ab88f10957b06a7

```
error:
/reactstrap/src/setupTests.js:3
    import Enzyme, { ReactWrapper } from 'enzyme';
    SyntaxError: Unexpected identifier
```

notes:
Worked on version 0.0.28 of jest.

bit.json && bitmap:
[reactstrap_bitmap_bitjson.tar.gz](https://github.com/teambit/bit-envs/files/2522704/reactstrap_bitmap_bitjson.tar.gz)

**Comment by GiladShoham** [comment]
@guysaar223  please check with recent jest and update here

**Comment by guysaar223** [comment]
not i'm getting this error:
` Module ts-jest in the transform option was not found.`
https://github.com/teambit/bit-envs/issues/77

**Comment by GiladShoham** [comment]
The last issue described by @guysaar223 has been fixed and we back to the problem with the setup file

**Comment by GiladShoham** [comment]
Some update info:
bit.json
```js
{
    "env": {
        "compiler": {
            "bit.test-envs/compilers/babel@1.0.1" : {
                "rawConfig": {
                    "useDefaultConfig": true
                }
            }
        },
        "tester": "bit.test-envs/testers/jest@0.9.12"
    },
    "dependencies": {},
    "componentsDefaultDirectory": "components/{name}",
    "packageManager": "npm"
}
```
we need to use the default config to cmopile since their babelrc file has the modules false in the preset configuration so it won't transform imports to require.

Another thing need to be done to get the error is to compile the index file (or add it as component).
We skip the index file as component (bit's feature) which create a case when it's not available in the dists (which cause requires point to it to fail). this is bug in bit and not part of this issue.
The easiast way to workaround this is to run (after bit build):
```bash
babel ./src/index.js --out-file ./dist/src/index.js
```
then when running bit test you will get an error:
```bash
PaginationLink › should render default `a` tag when `href` is present


          Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.
          To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:

          import Adapter from 'enzyme-adapter-react-15';

          To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html

      13 | describe('PaginationLink', function () {
      14 |   it('should render default `a` tag when `href` is present', function () {
    > 15 |     var wrapper = (0, _enzyme.mount)(_react2.default.createElement(_.PaginationLink, { href: '#' }));
         |                   ^
      16 |
      17 |     expect(wrapper.find('a').hostNodes().length).toBe(1);
      18 |   });


      at validateAdapter (node_modules/enzyme/build/validateAdapter.js:16:11)
      at getAdapter (node_modules/enzyme/build/getAdapter.js:27:36)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:122:49)
      at mount (node_modules/enzyme/build/mount.js:21:10)
      at Object.<anonymous> (dist/src/__tests__/PaginationLink.spec.js:15:19)
```
The adapter is defined in the src/setupTests.js but this file is not loaded any time.
