### ISSUE TITLE
Cannot find module /jest-cli

### ISSUE THREAD

**Issue by guysaar223** [teambit/bit-envs#74]
to reproduce:
1. download the tar:
https://drive.google.com/open?id=1NwdrqCTjE83ZMgntcbsajEH4W9RwLcNn
2. bit build
3. bit test 

```
error: bit failed to test internal/date-helpers with the following exception:
Command failed: /Users/guysaar/dev/belle/.bitTmp/execute-jest.js --config '{"jest":{"testRunner":"jasmine2","automock":true,"unmockedModulePathPatterns":["<rootDir>/node_modules/react","<rootDir>/node_modules/fbjs","<rootDir>/node_modules/react-dom","<rootDir>/node_modules/prop-types","../utils/helpers","../utils/union-class-names","../utils/is-component-of-type"],"scriptPreprocessor":"<rootDir>/node_modules/babel-jest"}}' --json /Users/guysaar/dev/belle/dist/src/__tests__/date-helpers-test.js > /Users/guysaar/dev/belle/.bitTmp/jestResults.json
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/guysaar/dev/belle/.git/bit/components/testers/jest/bit.test-envs/0.9.10/node_modules/jest-cli/build/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/guysaar/dev/belle/.bitTmp/execute-jest.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Error: Command failed: /Users/guysaar/dev/belle/.bitTmp/execute-jest.js --config '{"jest":{"testRunner":"jasmine2","automock":true,"unmockedModulePathPatterns":["<rootDir>/node_modules/react","<rootDir>/node_modules/fbjs","<rootDir>/node_modules/react-dom","<rootDir>/node_modules/prop-types","../utils/helpers","../utils/union-class-names","../utils/is-component-of-type"],"scriptPreprocessor":"<rootDir>/node_modules/babel-jest"}}' --json /Users/guysaar/dev/belle/dist/src/__tests__/date-helpers-test.js > /Users/guysaar/dev/belle/.bitTmp/jestResults.json
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/guysaar/dev/belle/.git/bit/components/testers/jest/bit.test-envs/0.9.10/node_modules/jest-cli/build/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/guysaar/dev/belle/.bitTmp/execute-jest.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

    at checkExecSyncError (child_process.js:600:11)
    at Object.execSync (child_process.js:637:13)
    at TesterExtension.action (/Users/guysaar/dev/belle/.git/bit/components/testers/jest/bit.test-envs/0.9.10/dist/src/jest/jest.js:42:37)
    at Component._callee6$ (/usr/local/lib/node_modules/bit-bin/dist/consumer/component/consumer-component.js:1028:43)
    at tryCatch (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/bit-bin/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/bit-bin/dist/consumer/component/consumer-component.js:343:191)
    at /usr/local/lib/node_modules/bit-bin/dist/consumer/component/consumer-component.js:343:437
    at new Promise (<anonymous>)
```

**Comment by GiladShoham** [comment]
@guysaar223  should be fixed now with version 0.9.11 please check
