### ISSUE TITLE
Bit test work localy, but not work in the CI

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit-envs#85]
react-foundation test work localy, but not work in the ci.
[react-foundation.tar.gz](https://github.com/teambit/bit-envs/files/2557886/react-foundation.tar.gz)

this is the error:
Error: Cannot find module '/tmp/5be2f8c82fc27b0018cc3dc8/environment/58524fcc-c8e2-4811-92d2-4cc7181af28d/test/index.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /tmp/5be2f8c82fc27b0018cc3dc8/components/testers/mocha/bit.test-envs/1.0.3/dist/src/mocha/mocha.js:45:17
    at Array.forEach (<anonymous>)
    at TesterExtension.action (/tmp/5be2f8c82fc27b0018cc3dc8/components/testers/mocha/bit.test-envs/1.0.3/dist/src/mocha/mocha.js:44:74)
    at Component._callee6$ (/usr/local/share/.config/yarn/global/node_modules/bit-bin/dist/consumer/component/consumer-component.js:1028:43)
    at tryCatch (/usr/local/share/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/share/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:296:22)
-------------------------------------Error-----------------------------------------

**Comment by GiladShoham** [comment]
The scope from bitsrc is here
Just download, extract and run `bit ci-update joshk.react-foundation/badge`
[joshk.react-foundation.scope.zip](https://github.com/teambit/bit-envs/files/2558110/joshk.react-foundation.scope.zip)

**Comment by GiladShoham** [comment]
An even easier reproduce for debuging - 
```bash
mkdir work-dir
cd work-dir
bd remote add file:///tmp/joshk.react-foundation.scope
bd import joshk.react-foundation/badge
bd test -a
```
You can even run the import with --conf then add the options.file and point it to the test-envs project so you can really enjoy:)

**Comment by GiladShoham** [comment]
If you don't want the .bitTmp folder to be deleted put this lines in a comment:
https://github.com/teambit/bit/blob/master/src/consumer/component/consumer-component.js#L689
https://github.com/teambit/bit/blob/master/src/consumer/consumer.js#L993
